server:
  port: 8082
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        fail-fast: false
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:127.0.0.1:9092}
      bindings:
        order-out-0:
          destination: order-topic
        productInput-in-0:
          destination: product-topic
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

seata:
  enabled: false

logging:
  level:
    root: INFO
