server:
  port: 8081
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        fail-fast: false
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:127.0.0.1:9092}
      bindings:
        product-out-0:
          destination: product-topic
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

# Seata 默认关闭，避免未搭建环境启动报错
seata:
  enabled: false

logging:
  level:
    root: INFO
